# Generated by Django 4.2.3 on 2023-09-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('BUILDING_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('WOJEWODZTWO', models.CharField(max_length=100)),
                ('COMUNITY', models.CharField(max_length=100)),
                ('CITY_NAME', models.CharField(max_length=100)),
                ('STREET_NAME', models.CharField(max_length=100)),
                ('BUILDING_NUMBER', models.CharField(max_length=10)),
                ('BUILDING_POST_CODE', models.CharField(max_length=10)),
                ('HP', models.CharField(max_length=100)),
                ('NET_NMBR', models.CharField(max_length=100)),
                ('PENETRACJA', models.CharField(max_length=100)),
                ('BITRATE', models.CharField(max_length=100)),
                ('Zakres_Predkosci', models.CharField(max_length=100)),
                ('CZARNA_LISTA', models.CharField(max_length=100)),
                ('NAJ_TECHNOLOGIA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('telewizja_internet', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('telefon', models.BooleanField(default=False)),
                ('internet_premium', models.BooleanField(default=False)),
                ('BI', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('telewizja_internet', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('telefon', models.BooleanField(default=False)),
                ('internet_premium', models.BooleanField(default=False)),
                ('BI', models.BooleanField(default=True)),
                ('sprzedawca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='wyszukiwarka_ulic.salesman')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=100)),
                ('numer_bloku', models.CharField(default='', max_length=10)),
                ('numer_mieszkania', models.CharField(default='', max_length=10)),
                ('kod_pocztowy', models.CharField(max_length=10)),
                ('for_sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='wyszukiwarka_ulic.forsale')),
            ],
        ),
        migrations.CreateModel(
            name='StreetOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyszukiwarka_ulic.offer')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyszukiwarka_ulic.street')),
            ],
        ),
        migrations.AddField(
            model_name='street',
            name='offers',
            field=models.ManyToManyField(related_name='streets', related_query_name='street', through='wyszukiwarka_ulic.StreetOffer', to='wyszukiwarka_ulic.offer'),
        ),
        migrations.AddField(
            model_name='street',
            name='sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='wyszukiwarka_ulic.sell'),
        ),
    ]
