# Generated by Django 4.2.3 on 2023-09-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyszukiwarka_ulic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='BITRATE',
            new_name='bitrate',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='BUILDING_ID',
            new_name='building_id',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='BUILDING_NUMBER',
            new_name='building_number',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='BUILDING_POST_CODE',
            new_name='building_post_code',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='CITY_NAME',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='COMUNITY',
            new_name='comunity',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='CZARNA_LISTA',
            new_name='czarna_lista',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='HP',
            new_name='hp',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='NAJ_TECHNOLOGIA',
            new_name='naj_technologia',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='NET_NMBR',
            new_name='net_nmbr',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='PENETRACJA',
            new_name='penetracja',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='STREET_NAME',
            new_name='street_name',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='WOJEWODZTWO',
            new_name='wojewodztwo',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='Zakres_Predkosci',
            new_name='zakres_predkosci',
        ),
    ]
